name: Unit Tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Download Dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: src/backend/database

      - name: Run Unit Tests
        run: |
          cd ${{ github.workspace }}/src/backend/database
          yarn test
